version: 2
updates:
- directory: /
  open-pull-requests-limit: 10
  package-ecosystem: npm
  rebase-strategy: auto
  schedule:
    interval: daily
  commit-message:
    prefix: chore
    include: scope
- directory: /
  open-pull-requests-limit: 1
  package-ecosystem: docker
  rebase-strategy: auto
  schedule:
    interval: weekly
  commit-message:
    prefix: chore
    include: scope
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: daily
  open-pull-requests-limit: 10
